CREATE FUNCTION fn_FormatDate_MMDDYYYY (@InputDate DATETIME)
RETURNS VARCHAR(10)
AS
BEGIN
    RETURN FORMAT(@InputDate, 'MM/dd/yyyy');
END;
GO

CREATE FUNCTION fn_FormatDate_YYYYMMDD (@InputDate DATETIME)
RETURNS VARCHAR(8)
AS
BEGIN
    RETURN FORMAT(@InputDate, 'yyyyMMdd');
END;
GO